apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-html-deployments
  labels:
    app: app-html
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app-html
  template:
    metadata:
      labels:
        app: app-html
    spec:
      containers:
      - name: app-html # Esse tem que ser igual ao do pod
        image: httpd:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
