apiVersion: v1
kind: Pod
metadata:
  name: pod-html
  labels:
    name: pod-html
spec:
  containers:
  - name: pod-html
    image: httpd:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
