# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: fileserver-httpd
# spec:
#   capacity:
#     storage: 50Gi
#   accessModes:
#   - ReadWriteMany
#   nfs:
#     path: /dados
#     server: 10.194.250.130
    
# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: fileserver-httpd
# spec:
#   accessModes:
#   - ReadWriteMany
#   storageClassName: ""
#   volumeName: fileserver-httpd
#   resources:
#     requests:
#       storage: 50Gi

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: httpd
# spec:
#   replicas: 6
#   selector:
#     matchLabels:
#       app: httpd
#   template:
#     metadata:
#       labels:
#         app: httpd
#     spec:
#       containers:
#       - image: httpd:latest
#         name: httpd
#         ports:
#         - containerPort: 80
#           name: httpd
        
#         volumeMounts:
#         - name: fileserver-httpd
#           mountPath: /usr/local/apache2/htdocs/
#       volumes:
#       - name: fileserver-httpd
#         persistentVolumeClaim:
#           claimName: fileserver-httpd


apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileserver-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /dados
    server: 10.194.250.130

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileserver-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: fileserver-pv # precisa ser o msm nome do pv
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 6
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - image: httpd:latest
        name: httpd
        ports:
        - containerPort: 80
          name: httpd

        volumeMounts:
        - name: fileserver
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: fileserver
        persistentVolumeClaim:
          claimName: fileserver-pvc # precisa ser do pvc
